//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mameui.rc
//
#define IDPAUSE                         3
#define IDS_UI_FILE                     61
#define IDS_UI_VIEW                     62
#define IDS_UI_OPTIONS                  63
#define IDS_UI_HELP                     64
#define IDS_VIEW_TOOLBAR                70
#define IDS_VIEW_STATUSBAR              71
#define IDS_VIEW_FOLDERLIST             72
#define IDS_VIEW_SCREENSHOT             73
#define IDS_VIEW_PICTURETABS            74
#define IDS_VIEW_SPACER1                75
#define IDS_VIEW_FULLSCREEN             76
#define IDS_VIEW_SPACER2                77
#define IDS_VIEW_SHOWPICTURES           78
#define IDS_VIEW_SPACER3                79
#define IDS_VIEW_LARGEICONS             80
#define IDS_VIEW_SMALLICONS             81
#define IDS_VIEW_LIST                   82
#define IDS_VIEW_DETAILS                83
#define IDS_VIEW_GROUPED                84
#define IDS_VIEW_SPACER4                85
#define IDS_VIEW_ARRANGE                86
#define IDS_VIEW_LINEUPICONS            87
#define IDS_VIEW_SPACER5                88
#define IDS_VIEW_REFRESH                89
#define IDS_VIEW_CONTEXTFILTERS         90
#define IDS_VIEW_CUSTOMIZEFIELDS        91
#define ID_TOOLBAR_EDIT                 92
#define IDD_MAIN                        101
#define IDA_TAB_KEYS                    106
#define IDI_MAMEUI_ICON                 107
#define IDD_ABOUT                       108
#define IDR_MAIN_MENU                   109
#define IDR_UI_MENU                     110
#define IDB_ABOUT                       113
#define IDD_DIRECTX                     114
#define IDD_AUDIT                       115
#define IDD_DIRECTORIES                 116
#define IDD_CUSTOM_FILE                 117
#define IDR_CONTEXT_MENU                118
#define IDI_WIN_NOROMS                  119
#define IDI_WIN_ROMS                    120
#define IDI_WIN_UNKNOWN                 121
#define IDI_WIN_CLONE                   122
#define IDI_WIN_REDX                    123
#define IDI_FOLDER_OPEN                 124
#define IDI_FOLDER                      125
#define IDI_FOLDER_AVAILABLE            126
#define IDI_FOLDER_MANUFACTURER         127
#define IDI_FOLDER_UNAVAILABLE          128
#define IDI_FOLDER_YEAR                 129
#define IDI_FOLDER_SOURCE               130
#define IDI_MANUFACTURER                131
#define IDI_WORKING                     132
#define IDI_NONWORKING                  133
#define IDI_YEAR                        134
#define IDI_SOUND                       135
#define IDI_CPU                         136
#define IDI_HARDDISK                    137
#define IDI_SOURCE                      138
#define IDI_FOLDER_HORIZONTAL           139
#define IDI_FOLDER_VERTICAL             140
#define IDR_CONTEXT_HEADER              151
#define IDD_PROP_GAME                   152
#define IDD_PROP_AUDIT                  153
#define IDD_PROP_DISPLAY                154
#define IDD_PROP_SOUND                  155
#define IDD_PROP_ADVANCED               156
#define IDD_PROP_INPUT                  157
#define IDD_PROP_MISC                   158
#define IDD_PROP_VECTOR                 159
#define IDD_COLUMNS                     160
#define IDI_KEYBOARD                    161
#define IDI_JOYSTICK                    162
#define IDI_DISPLAY                     163
#define IDI_CHECKMARK                   164
#define IDC_CURSOR_HSPLIT               165
#define IDB_TOOLBAR                     166
#define IDR_CONTEXT_TREE                168
#define IDD_FILTERS                     169
#define IDD_RESET                       170
#define IDD_LOAD_PROGRESS               171
#define IDD_INTERFACE_OPTIONS           173
#define IDR_CONTEXT_SCREENSHOT          181
#define IDI_HEADER_UP                   182
#define IDI_HEADER_DOWN                 183
#define IDD_PROP_CONTROLLER             185
#define IDD_PROP_SCREEN                 187
#define IDD_PROP_DEBUG                  188
#define IDI_SOUNDTAB                    666
#define IDC_LIST                        1000
#define IDC_JOYSTICK                    1003
#define IDC_SIZES                       1005
#define IDC_FRAMESKIP                   1009
#define IDC_ROTATE                      1010
#define IDC_SCREEN                      1012
#define IDC_VIEW                        1014
#define IDC_SCREENSELECT                1015
#define IDC_CHEAT                       1016
#define IDC_LOG                         1017
#define IDC_ARTWORK_CROP                1018
#define IDC_OVERLAYS                    1019
#define IDC_BEZELS                      1021
#define IDC_SLEEP                       1022
#define IDC_GAMMA                       1023
#define IDC_BRIGHTCORRECT               1024
#define IDC_USE_DEFAULT                 1025
#define IDC_CONTRAST                    1026
#define IDC_SAMPLERATE                  1027
#define IDC_NUMSCREENS                  1028
#define IDC_ANTIALIAS                   1029
#define IDC_BEAM                        1030
#define IDC_FLICKER                     1031
#define IDC_FLIPX                       1032
#define IDC_FLIPY                       1033
#define IDC_BACKDROPS                   1034
#define IDC_DIRECTX_HELP                1035
#define IDC_FLICKERDISP                 1036
#define IDB_WEB_PAGE                    1037
#define IDC_FSCONTRAST                  1038
#define IDC_ROMS_PROGRESS               1039
#define IDC_SECONDSTORUN                1039
#define IDC_CONTRASTDISP                1040
#define IDC_ROMS_CORRECT                1041
#define IDC_FSCONTRASTDISP              1042
#define IDC_ROMS_INCORRECT              1043
#define IDC_SECONDSTORUNDISP            1043
#define IDC_NUMSCREENSDISP              1044
#define IDC_ROMS_TOTAL                  1045
#define IDC_SAMPLES_PROGRESS            1046
#define IDC_SAMPLES_CORRECT             1047
#define IDC_BEAMDISP                    1048
#define IDC_SAMPLES_INCORRECT           1049
#define IDC_SAMPLES_TOTAL               1050
#define IDC_AUDIT_DETAILS               1051
#define IDC_DIR_COMBO                   1053
#define IDC_DIR_LIST                    1054
#define IDC_DIR_BROWSE                  1055
#define IDC_DIR_INSERT                  1056
#define IDC_DIR_DELETE                  1057
#define IDC_FLICKERTEXT                 1058
#define IDC_SSFRAME                     1059
#define IDC_PRESCALE                    1060
#define IDC_SSPICTURE                   1062
#define IDC_BEAMTEXT                    1063
#define IDC_MULTIKEYBOARD               1065
#define IDC_RATETEXT                    1069
#define IDC_LISTAVAILABLECOLUMNS        1070
#define IDC_LISTSHOWCOLUMNS             1071
#define IDC_BUTTONADD                   1072
#define IDC_BUTTONREMOVE                1073
#define IDC_BUTTONMOVEDOWN              1074
#define IDC_BUTTONMOVEUP                1075
#define IDC_PROP_SOUND                  1076
#define IDC_PROP_CPU                    1077
#define IDC_PROP_TITLE                  1078
#define IDC_PROP_MANUFACTURED           1079
#define IDC_PROP_STATUS                 1080
#define IDC_PROP_SCREEN                 1081
#define IDC_PROP_COLORS                 1082
#define IDC_PROP_ROMS                   1083
#define IDC_PROP_SAMPLES                1084
#define IDC_PROP_CLONEOF_TEXT           1085
#define IDC_PROP_CLONEOF                1086
#define IDC_VERSION                     1088
#define IDC_FSGAMMA                     1090
#define IDC_GAMMADISP                   1091
#define IDC_FSBRIGHTNESS                1092
#define IDC_FSGAMMADISP                 1093
#define IDC_PRESCALEDISP                1094
#define IDC_BRIGHTCORRECTDISP           1095
#define IDC_FSBRIGHTNESSDISP            1096
#define IDC_AUTOFRAMESKIP               1097
#define IDC_TREE                        1098
#define IDC_WINDOWED                    1099
#define IDC_PROP_RESET                  1101
#define IDC_SPLITTER                    1102
#define IDC_SPLITTER2                   1103
#define IDC_DIVIDER                     1104
#define IDC_FILTER_VECTOR               1105
#define IDC_FILTER_RASTER               1106
#define IDC_FILTER_UNAVAILABLE          1107
#define IDC_FILTER_NONWORKING           1108
#define IDC_FILTER_CLONES               1109
#define IDC_RESET_GAMES                 1110
#define IDC_RESET_UI                    1111
#define IDC_RESET_FILTERS               1112
#define IDC_RESET_EFFECT                1113
#define IDC_RESET_DEFAULT               1114
#define IDC_FILTER_ORIGINALS            1115
#define IDC_FILTER_WORKING              1116
#define IDC_FILTER_AVAILABLE            1117
#define IDC_START_GAME_CHECK            1120
#define IDC_VOLUME                      1121
#define IDC_VOLUMEDISP                  1122
#define IDC_HISTORY                     1124
#define IDC_SAMPLES                     1125
#define IDC_TRIPLE_BUFFER               1127
#define IDC_LOAD_ROMNAME                1128
#define IDC_DEFAULT_INPUT               1129
#define IDC_LANGUAGECHECK               1130
#define IDC_LANGUAGEBROWSE              1131
#define IDC_LANGUAGEEDIT                1132
#define IDC_FILTER_EDIT                 1133
#define IDC_ABOUT                       1134
#define IDC_USE_SOUND                   1136
#define IDC_WAITVSYNC                   1137
#define IDC_HWSTRETCH                   1138
#define IDC_SWITCHRES                   1139
#define IDC_MAXIMIZE                    1140
#define IDC_KEEPASPECT                  1141
#define IDC_SYNCREFRESH                 1142
#define IDC_USE_MOUSE                   1143
#define IDC_THROTTLE                    1144
#define IDC_VOLUMETEXT                  1146
#define IDC_REFRESH                     1148
#define IDC_REFRESHTEXT                 1149
#define IDC_EFFECT                      1150
#define IDC_FSGAMMATEXT                 1151
#define IDC_STEADYKEY                   1152
#define IDC_ASPECTRATION                1154
#define IDC_ASPECTRATIOD                1155
#define IDC_ASPECTRATIOTEXT             1156
#define IDC_JOY_GUI                     1157
#define IDC_BROADCAST                   1158
#define IDC_JDZ                         1159
#define IDC_JDZDISP                     1160
#define IDC_JDZTEXT                     1161
#define IDC_JSATTEXT                    1162
#define IDC_JSAT                        1163
#define IDC_JSATDISP                    1164
#define IDC_AUDIO_LATENCY_DISP          1165
#define IDC_PLAY_GAME                   1166
#define IDC_LIGHTGUN                    1167
#define IDC_SSTAB                       1168
#define IDC_GAME_ICON                   1169
#define IDC_RANDOM_BG                   1170
#define IDC_CUSTOM_TREE                 1171
#define IDC_CUSTOMFILE_GAME             1173
#define IDC_LOAD_STATUS                 1174
#define IDC_ERROR_TEXT                  1175
#define IDC_ARTMISCTEXT                 1176
#define IDC_ENABLE_AUTOSAVE             1177
#define IDC_SKIP_GAME_INFO              1178
#define IDC_PROP_SOURCE                 1179
#define IDC_FILTER_HORIZONTAL           1180
#define IDC_PAUSEBRIGHT                 1181
#define IDC_PAUSEBRIGHTDISP             1182
#define IDC_HIGH_PRIORITY               1183
#define IDC_D3D_FILTER                  1184
#define IDC_HIDE_MOUSE                  1185
#define IDC_AUDIO_LATENCY               1186
#define IDC_D3D_VERSION                 1187
#define IDC_AUDIT_DETAILS_PROP          1188
#define IDC_CYCLETIMESEC                1190
#define IDC_AUDIO_LATENCY_TEXT          1191
#define IDC_STRETCH_SCREENSHOT_LARGER   1192
#define IDC_FILTER_INHERIT              1193
#define IDC_RESET_PLAYTIME              1194
#define IDC_RESET_PLAYCOUNT             1195
#define IDC_INHERITED                   1196
#define IDC_KEY_GUI                     1197
#define IDC_RELOAD                      1198
#define IDC_DUAL_LIGHTGUN               1199
#define IDC_NOOFFSET_CLONES             1200
#define IDC_BIOS                        1201
#define IDC_HISTORY_TAB                 1202
#define IDC_SNAPVIEW                    1202
#define IDC_SCREENSHOT_BORDERSIZE       1204
#define IDC_SCREENSHOT_BORDERCOLOR      1205
#define IDC_CYCLETIMESECTXT             1206
#define IDC_SCREENSHOT_BORDERSIZETXT    1207
#define IDC_PADDLE                      1208
#define IDC_ADSTICK                     1209
#define IDC_PEDAL                       1210
#define IDC_DIAL                        1211
#define IDC_TRACKBALL                   1212
#define IDC_LIGHTGUNDEVICE              1213
#define IDC_MOUSE                       1214
#define IDC_POSITIONAL                  1215
#define IDC_HIGH_PRIORITY_TEXT          1216
#define IDC_HIGH_PRIORITYTXT            1217
#define IDC_SELECT_EFFECT               1218
#define IDC_MULTITHREAD_RENDERING       1219
#define IDC_ASPECT                      1220
#define IDC_LOAD_PROGRESS               1223
#define IDC_FSBRIGHTNESSTEXT            1224
#define IDC_FSCONTRASTTEXT              1225
#define IDC_VIDEO_MODE                  1226
#define IDC_SCREENSELECTTEXT            1227
#define IDC_MULTIMOUSE                  1230
#define IDC_DEBUG                       1231
#define IDC_REFRESHSPEED                1232
#define IDC_SPEEDTEXT                   1233
#define IDC_SPEED                       1234
#define IDC_SPEEDDISP                   1235
#define IDC_FILTER_VERTICAL             1236
#define IDC_SNAPNAME                    1237
#define IDC_COINLOCKOUT                 1238
#define IDC_SECONDSTORUNTEXT            1239
#define IDC_OSLOG                       1240
#define IDC_VERBOSE                     1241
#define IDC_UPDATEINPAUSE               1242
#define IDC_DEBUGSCRIPT                 1243
#define IDC_SELECT_DEBUGSCRIPT          1244
#define IDC_RESET_DEBUGSCRIPT           1245
#define IDC_SELECT_JOYSTICKMAP          1246
#define IDC_RESET_JOYSTICKMAP           1247
#define IDC_JOYSTICKMAP                 1248
#define IDC_SNAPSIZE                    1249
#define IDC_SNAPSIZEWIDTH               1250
#define IDC_SNAPSIZEHEIGHT              1251
#define IDC_SNAPSIZETEXT                1252
#define IDC_SNAPSIZEX                   1253
#define IDC_FILTER_MECHANICAL           1254
#define ID_CONTEXT_SHOW_FOLDER_START    39000
#define ID_CONTEXT_SHOW_FOLDER_END      39200
#define ID_FILE_EXIT                    40001
#define ID_ABOUT                        40003
#define ID_FILE_PLAY                    40004
#define ID_HELP_ABOUT                   40006
#define ID_VIEW_LARGE_ICON              40007
#define ID_VIEW_SMALL_ICON              40008
#define ID_VIEW_LIST_MENU               40009
#define ID_VIEW_DETAIL                  40010
#define ID_VIEW_GROUPED                 40011
#define ID_OPTIONS_FONT                 40012
#define ID_OPTIONS_CLONE_COLOR          40013
#define ID_OPTIONS_DIR                  40014
#define ID_OPTIONS_DEFAULTS             40015
#define ID_OPTIONS_RESET_DEFAULTS       40016
#define ID_OPTIONS_INTERFACE            40017
#define ID_FILE_AUDIT                   40018
#define ID_FILE_PLAY_RECORD             40019
#define ID_FILE_PLAY_BACK               40020
#define ID_FILE_PLAY_RECORD_WAVE        40021
#define ID_FILE_PLAY_RECORD_MNG         40022
#define ID_FILE_PLAY_RECORD_AVI         40023
#define ID_VIEW_PICTURE_AREA            40024
#define ID_HELP_CONTENTS                40025
#define ID_HELP_WHATS_NEWUI             40026
#define ID_HELP_TROUBLE                 40027
#define ID_HELP_RELEASE                 40028
#define ID_HELP_WHATS_NEW               40029
#define ID_HELP_CHEATS                  40030
#define ID_VIEW_BYGAME                  40034
#define ID_VIEW_BYDIRECTORY             40035
#define ID_VIEW_BYMANUFACTURER          40036
#define ID_VIEW_BYYEAR                  40037
#define ID_VIEW_BYTYPE                  40038
#define ID_VIEW_BYTIMESPLAYED           40039
#define ID_VIEW_LINEUPICONS             40040
#define ID_UPDATE_GAMELIST              40042
#define ID_SORT_ASCENDING               40045
#define ID_SORT_DESCENDING              40046
#define ID_CUSTOMIZE_FIELDS             40048
#define ID_GAME_PROPERTIES              40049
#define ID_VIEW_PAGETAB                 40050
#define ID_VIEW_FOLDERS                 40051
#define ID_VIEW_TOOLBARS                40052
#define ID_VIEW_STATUS                  40053
#define ID_CONTEXT_FILTERS              40054
#define ID_CONTEXT_RENAME_CUSTOM        40055
#define ID_CONTEXT_ADD_CUSTOM           40057
#define ID_CONTEXT_REMOVE_CUSTOM        40058
#define ID_GAME_AUDIT                   40059
#define ID_CONTEXT_SELECT_RANDOM        40060
#define ID_VIEW_TAB_SCREENSHOT          40062
#define ID_VIEW_TAB_FLYER               40063
#define ID_VIEW_TAB_CABINET             40064
#define ID_VIEW_TAB_MARQUEE             40065
#define ID_VIEW_TAB_TITLE               40066
#define ID_VIEW_TAB_CONTROL_PANEL       40067
#define ID_VIEW_TAB_PCB                 40068
#define ID_VIEW_TAB_HISTORY             40069
#define ID_OPTIONS_BG                   40070
#define ID_TOGGLE_TAB_SCREENSHOT        40071
#define ID_TOGGLE_TAB_FLYER             40072
#define ID_TOGGLE_TAB_CABINET           40073
#define ID_TOGGLE_TAB_MARQUEE           40074
#define ID_TOGGLE_TAB_TITLE             40075
#define ID_TOGGLE_TAB_CONTROL_PANEL     40076
#define ID_TOGGLE_TAB_PCB               40077
#define ID_TOGGLE_TAB_HISTORY           40078
#define ID_VIEW_FULLSCREEN              40079
#define ID_CONTEXT_RESET_PLAYTIME       40080
#define ID_CONTEXT_RESET_PLAYCOUNT      40081
#define ID_FOLDER_PROPERTIES            40082
#define ID_FOLDER_AUDIT                 40083
#define ID_UI_UP                        40084
#define ID_UI_DOWN                      40085
#define ID_UI_LEFT                      40086
#define ID_UI_RIGHT                     40087
#define ID_UI_START                     40088
#define ID_UI_PGUP                      40089
#define ID_UI_PGDOWN                    40090
#define ID_UI_HOME                      40091
#define ID_UI_END                       40092
#define ID_UI_HISTORY_UP                40093
#define ID_UI_HISTORY_DOWN              40094
#define ID_FILE_LOADSTATE               40095
#define ID_FOLDER_SOURCEPROPERTIES      40096
#define ID_FOLDER_VECTORPROPERTIES      40097
#define ID_OPTIONS_CHEAT                40099
#define ID_OPTIONS_MAMEINFO             40100
#define ID_OPTIONS_HISTORY              40101
#define ID_VIEW_SOFTWARE_AREA           40102
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        192
#define _APS_NEXT_COMMAND_VALUE         40103
#define _APS_NEXT_CONTROL_VALUE         1255
#define _APS_NEXT_SYMED_VALUE           93
#endif
#endif
